'use client'

import { createContext, ReactNode, useContext, useState } from 'react'

type Language = 'EN' | 'FR'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations: Record<Language, Record<string, string>> = {
  EN: {
    'nav.about': 'About',
    'nav.portfolio': 'Portfolio',
    'nav.services': 'Services',
    'nav.pricing': 'Pricing',
    'nav.faq': 'FAQ',
    'nav.blog': 'Blog',
    'nav.menu': 'Menu',
    'nav.contact': 'Contact',
    'hero.status': 'Available for new projects',
    'hero.title_p1': 'Crafting digital',
    'hero.title_p2': 'ecosystems',
    'hero.title_p3': 'for modern brands.',
    'hero.desc':
      'We operate at the intersection of elegant design, cutting-edge technology, and profound strategy to create brand experiences that captivate and convert.',
    'hero.cta_work': 'View our work',
    'hero.cta_services': 'Our Services',
    'hero.stat_startups': 'Startups Funded',
    'hero.stat_awards': 'Industry Awards',
    'work.tagline': 'How we innovate.',
    'work.desc':
      'A highly refined, four-step methodology designed to transform your vision into a world-class digital experience.',
    'work.step1.title': 'Strategy',
    'work.step1.desc':
      "Discovering your brand's core values, target audience, and positioning to lay a solid foundation for growth.",
    'work.step2.title': 'Wireframing',
    'work.step2.desc':
      'Mapping out the user journey and structural layout to ensure a seamless and intuitive user experience.',
    'work.step3.title': 'Design',
    'work.step3.desc':
      'Crafting a visually stunning and highly polished elegant interface that resonates with your users.',
    'work.step4.title': 'Development',
    'work.step4.desc':
      'Engineering scalable, high-performance solutions using the latest tech stacks and elegant motion.',
    'projects.title': 'Selected',
    'projects.title_italic': 'works.',
    'projects.cta': 'View Directory',
    'services.title': 'Comprehensive',
    'services.title_italic': 'solutions',
    'services.title_p2': 'to grow your brand.',
    'services.desc':
      'We provide a complete suite of elegant digital services tailored for modern startups and enterprises.',
    'faq.title': 'System',
    'faq.title_italic': 'Inquiries.',
    'faq.tagline': 'Frequently Asked Questions',
    'faq.main_title': 'Common inquiries,',
    'faq.title_italic_resolved': 'resolved.',
    'faq.desc':
      'Find answers regarding project processing times, headless performance speed configurations, design workflows, and milestone payment schedules.',
    'faq.search_placeholder': 'Search timelines, tech stack, GMB, payments...',
    'faq.items.timeline.q': 'How much time does a typical project take?',
    'faq.items.timeline.a':
      'Most custom web development and brand storytelling projects span between 4 to 8 weeks. Highly custom applications with advanced multi-agent integrations can require 10 to 14 weeks from initial diagnostic audit to live deployment.',
    'faq.items.kickoff.q': 'What is your typical project kickoff workflow?',
    'faq.items.kickoff.a':
      'We start with a thorough Landscape Audit of your competitors, page speeds, and technical requirements. Once the Blueprint phase is finalized, we build responsive visual wireframes, moving into pixel-perfect development and edge performance benchmarking.',
    'faq.items.comms.q': 'How do you handle communications and file sharing?',
    'faq.items.comms.a':
      'We assign a dedicated Slack workspace and hold weekly video reviews. All designs are fully viewable on Figma, and our development logs are regularly pushed to staging environments for active monitoring and testing.',
    'faq.items.figma.q': 'Do you design files in Figma, or code directly?',
    'faq.items.figma.a':
      'We do both. We build robust layout design systems inside Figma so you can easily visual brand elements, copy blocks, and interactions. Once approved, we build them into clean code using modular React, Webflow, or Shopify modules.',
    'faq.items.shopify.q': 'Can you help optimize our Shopify store margins?',
    'faq.items.shopify.a':
      'Yes. We create customized headless e-commerce storefronts using Shopify Storefront API paired with fast CMS systems like Sanity. By caching catalog states globally on Edge networks, we reduce load times, improve search visibility, and increase checkout completions.',
    'faq.items.gmb.q': 'What does GMB Map Stack ranking optimization include?',
    'faq.items.gmb.a':
      'Our local SEO maps sequence audits duplicate coordinates, aligns citation naming conventions, configures localized schema data, and structures automated local review processes. This local prominence places your locations in the Top-3 Local Pack, driving real customer walk-ins.',
    'faq.items.headless.q': 'Why do you prefer decoupled and headless development patterns?',
    'faq.items.headless.a':
      'Decoupled web structures split the presentation layer from the database back-end. This means database operations never lock or delay page visual loads. Performance increases, page weights drop below 200KB, and security is tighter.',
    'faq.items.security.q': 'I have sensitive databases. How do you protect API keys?',
    'faq.items.security.a':
      'We use secure multi-tier architectures where API keys (such as Gemini, Stripe, Salesforce tokens) always live on secluded node servers or serverless routing proxies. They are never sent to the client browser, preventing token exploitation.',
    'faq.items.motion.q': 'How does the sound and animation engine run so smoothly?',
    'faq.items.motion.a':
      'We avoid heavy video files. Canvas particles, book flips, and brand micro-interactions are written in pure SVG and programmatic vector path coordinates animated via lightweight libraries (like GSAP and Anime.js) operating on GPU threads.',
    'faq.items.billing_structure.q': 'What is your payment and milestone structure?',
    'faq.items.billing_structure.a':
      'We typically work on a clear milestone structure: 50% upfront to commence initial audits and blueprint visual layouts, and 50% upon final user validation and deployment.',
    'faq.items.maintenance.q': 'Do you offer post-launch maintenance, hosting, and support?',
    'faq.items.maintenance.a':
      'Absolutely. We offer tailored monthly retainer packages starting at $500/month which include security audits, dependency updates, content layout refreshes, and edge-traffic reports.',
    'faq.unresolved.tag': 'Unresolved Problem?',
    'faq.unresolved.title': 'Have specific queries concerning your business model?',
    'faq.unresolved.desc':
      'Our support partners and founders respond directly to custom project briefs within 12 hours. Submit details below or launch client chat directly on Slack.',
    'faq.unresolved.cta_brief': 'Establish Custom Project Brief',
    'faq.unresolved.cta_email': 'Direct Email',
    'faq.no_results': 'No matching queries found',
    'faq.no_results_desc':
      'We couldn\'t locate any answers targeting "{query}". Try searching other terms like "Shopify", "payments", or "timeline".',
    'faq.clear_filters': 'Clear Search filters',
    'blog.title': 'Latest',
    'blog.title_italic': 'Insights.',
    'blog.tagline': 'News & Editorial',
    'blog.main_title': 'Insights from the',
    'blog.title_italic_resolved': 'digital syndicate.',
    'blog.desc':
      'Documenting engineering milestones, micro-interaction benchmarks, vector file sizing formulas, and AI marketing workflows.',
    'blog.journal_tag': 'NextCreavo Journal',
    'blog.search_placeholder': 'Filter by keywords, tech, or design...',
    'blog.featured': 'FEATURED INSIGHT',
    'blog.read_article': 'Read Article',
    'blog.no_results': 'No insights found matching your query.',
    'blog.clear_filters': 'Clear filters',
    'contact.tagline': 'System Briefing Engine',
    'contact.title1': 'Initiate your design',
    'contact.title_italic': 'manifesto.',
    'contact.desc':
      'Submit your strategic requirements below. Our group of design architects, engineers, and digital systems specialists will construct your product roadmap.',
    'contact.form.name': 'Full Legal Name',
    'contact.form.email': 'Secure Email Address',
    'contact.form.service': 'Core Service Vertical',
    'contact.form.industry': 'Brand Industry Sector',
    'contact.form.budget': 'Target Resource Allocation',
    'contact.form.date': 'Ideal Implementation Date',
    'contact.form.message': 'Project Vision & Parameters',
    'contact.form.submit': 'Transmit Project Brief',
    'contact.form.submitting': 'Transmitting...',
    'contact.form.success_title': 'Brief Received Successfully.',
    'contact.form.success_desc':
      'Your project roadmap is being drafted. A strategist will contact you within 24 hours.',
    'contact.info.title': 'Support Coordinates',
    'contact.info.desc': 'Direct channels for immediate architectural support or global inquiries.',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    'footer.tagline': 'Have an idea?',
    'footer.tagline_secondary': "Let's build it.",
    'cta.brief': 'Initiate Project Brief',
    'cta.book': 'Book Meeting',
    'ui.social_feeds': 'Social Feeds',
    'ui.coordinates': 'Coordinates',
    'ui.system_navigation': 'System Navigation',
    'ui.available': 'Available for new projects',
    'testimonials.title': 'Executive',
    'testimonials.title_italic': 'Feedback.',
    'testimonials.tagline': 'Client Testimonials',
    'about.tagline': 'The NextCreavo Synthesis',
    'about.title1': 'Formulating digital',
    'about.title2': 'masterpieces with',
    'about.title_italic': 'artistry.',
    'about.desc':
      'Operating at the intersection of Swiss visual layouts, native multi-device performance, and intelligent agent pipelines. We build scalable digital products that reshape brand trajectories.',
    'about.hero_stats': 'Precision architecture curated in digital labs.',
    'about.values_tag': 'OUR COMPASS',
    'about.values_title': 'Uncompromising values,',
    'about.values_italic': 'engineered to inspire',
    'about.values_desc':
      'We reject visual templates and slow programming. Our team aligns behind four fundamental blueprints to deliver digital integrity.',
    'about.pipeline_tag': 'Our Pipeline',
    'about.pipeline_title': 'The pipeline of',
    'about.pipeline_italic': 'precision creation.',
    'about.pipeline_desc':
      'We structure our project lifecycle to minimize delays, optimize performance weight and guarantee pixel accuracy.',
    'about.mission_tag': 'OUR MISSION',
    'about.mission_title': 'To inspire, innovate, and elevate digital brands.',
    'about.mission_desc':
      'We design digital ecosystems that forge instant connections with worldwide partners. Our goal is to push visual boundaries, validate absolute performance statistics, and continuously share our methodologies.',
    'about.vision_tag': 'OUR VISION',
    'about.vision_title': 'Laser focused on visual perfection.',
    'about.vision_desc':
      'To be the premier digital agency recognized globally for an unwavering commitment to craftsmanship. NextCreavo treats every client engagement not as a standard contract, but as a potential design masterpiece.',
    'about.team_tag': 'The Strategists',
    'about.team_title': 'Meet the minds behind',
    'about.team_italic': 'the craft.',
    'about.team_desc':
      'A highly curated syndicate of global designers, fullstack builders, and digital marketers pacing digital breakthroughs.',
    'portfolio.listing_tag': 'Our Showcase',
    'portfolio.listing_title_part1': 'Bespoke design,',
    'portfolio.listing_title_part2': 'engineered to scale.',
    'portfolio.listing_desc':
      'Explore our record of digital masterpieces. We turn complex visual concepts into seamless business triumphs.',
    'portfolio.categories.all': 'All Projects',
    'portfolio.categories.animation': '2D Animation',
    'portfolio.categories.marketing': 'Digital Marketing',
    'portfolio.categories.webdev': 'Web Development',
    'portfolio.categories.appdev': 'App Development',
    'portfolio.categories.ai': 'AI & Integrations',
    'portfolio.categories.uiux': 'UI/UX Design',
    'portfolio.categories.desc.animation':
      'Logo Animation, Book Animation, and custom animated assets to bring your brand to life.',
    'portfolio.categories.desc.marketing':
      'GMB optimization (Map Ranking), Google Ads & Facebook Ads, Social Media management.',
    'portfolio.categories.desc.webdev':
      'Frontend, Backend & Full-Stack. Shopify, Webflow, WordPress, Squarespace, Headless CMS.',
    'portfolio.categories.desc.appdev':
      'Cross-platform and native mobile application development tailored for your needs.',
    'portfolio.categories.desc.ai': 'AI Agentic features, AI API integration, and advanced automation.',
    'portfolio.categories.desc.uiux': 'User-centric interface design and engaging user experiences for web and mobile.',
    'portfolio.viewer_tag': 'Architectural Asset',
    'portfolio.viewer_title': 'System Geometry 01',
    'portfolio.viewer_interactive': 'Interactive View',
    'portfolio.viewer_instructions': 'Drag to rotate / Scroll to zoom',
    'portfolio.share_case': 'Share Case Study',
    'portfolio.ready_inspect_next': 'Ready to inspect our next triumph:',
    'portfolio.see_how_resolved':
      'See how we resolved severe latency parameters and structured localized design blueprints for',
    'portfolio.launch_next': 'Launch next case study',
    'portfolio.conclusion_milestone': 'Conclusion Milestone',
    'portfolio.ready_replicate': 'Ready to replicate this calibre of success?',
    'portfolio.connect_desc':
      'Connect with our strategists to discuss how custom layout architectures or programmatic workflows can elevate your brand equity.',
    'portfolio.search_placeholder': 'Search projects, stack, tags...',
    'portfolio.no_results': 'No matching archives found.',
    'portfolio.clear_filters': 'Clear all filters',
    'portfolio.tags_tag': 'Tags & Tooling',
    'portfolio.client_tag': 'Client Partner',
    'portfolio.timeline_tag': 'Implementation Span',
    'portfolio.challenge_tag': 'The Strategic Challenge',
    'portfolio.solution_tag': 'The Technical Response',
    'portfolio.results_tag': 'KPI Outcomes & Benchmarks',
    'portfolio.title': 'The Showcase',
    'portfolio.tagline': 'Crafting digital ecosystems for modern brands.',
    'portfolio.back_to_grid': 'Back to Showcase Grid',
    'portfolio.prev_case': 'Prev Case',
    'portfolio.next_case': 'Next Case',
    'portfolio.desktop_pre': 'Desktop Pre',
    'portfolio.mobile_pre': 'Mobile Pre',
    'portfolio.client_chronicle': 'Client Success Chronicle',
    'portfolio.account_partner': 'Account Partner',
    'portfolio.transit_timeline': 'Transit Timeline',
    'portfolio.live_link': 'Live Environment Link',
    'portfolio.strategic_brief': 'Strategic Diagnostics Brief',
    'portfolio.pinnacle_obstacle': 'Pinnacle Obstacle',
    'portfolio.technical_formulation': 'Technical Formulation',
    'portfolio.verified_outcomes': 'Verified Outcome Objectives',
    'portfolio.aesthetic_swatches': 'Aesthetic Formula Swatches',
    'portfolio.aesthetic_desc':
      'Unique visual direction structured in alignment with user visual ergonomics. Click any swatch coordinate to copy values instantly.',
    'portfolio.workflow_roadmap': 'Workflow Roadmap',
    'portfolio.infrastructure_toolkit': 'Infrastructure Ingredient Toolkit',
    'portfolio.infrastructure_desc':
      'Architected using state-of-the-art developer standards to guarantee responsiveness, light bandwidth weights, and high performance.',
    'portfolio.launch_live': 'Launch Live Experience',
    'portfolio.return_to_directory': 'Return to Directory',
    'portfolio.next_chronicle': 'NEXT CASE STUDY CHRONICLE',
    'portfolio.interactive_grid': 'interactive grid layout',
    'portfolio.designed_by_desc':
      'Designed, compressed, and programmed by NextCreavo to work smoothly across low network grids and high-latency mobile conditions.',
    'portfolio.hover_to_scroll': 'Hover to Scroll',
    'portfolio.category_overview': 'Category Overview',
    'portfolio.interactive_case_studio': 'Interactive Case Studio',
    'portfolio.no_projects_found': 'No matching projects found',
    'portfolio.no_projects_desc_part1': 'We couldn’t locate any achievements for ',
    'portfolio.no_projects_desc_part2': 'in the selected category. Check spelling or clear search filters.',
    'portfolio.reset_filters': 'Reset All Filters',
    'cookies.title': 'Cookie Consent',
    'cookies.desc': 'This website uses cookies to enhance your experience and analyze our traffic.',
    'cookies.accept': 'Accept All',
    'cookies.details': 'Cookie Settings',
    'privacy.title': 'Privacy',
    'privacy.title_italic': 'Policy.',
    'privacy.last_updated': 'Last updated: June 11, 2026',
    'privacy.legal_directive': 'Legal Directive 01',
    'privacy.section1.title': '1. Information Collection',
    'privacy.section1.desc':
      'NextCreavo collects information necessary to provide bespoke digital services. This includes identifiers provided during the brief submission process and automated telemetry gathered during system navigation.',
    'privacy.section2.title': '2. Usage of Parameters',
    'privacy.section2.desc':
      'Your data is processed to facilitate project roadmap construction, stabilize system communications, and personalize the architectural experience. We do not transmit identifiers to third-party data ecosystems for advertising purposes.',
    'privacy.section3.title': '3. Security Architecture',
    'privacy.section3.desc':
      'We maintain a multi-layered security protocol. Transmission of briefs occurs over TLS 1.3 encrypted tunnels. Persistent data is segregated in guarded Cloud SQL and Firestore environments.',
    'privacy.stat1.title': 'Data Protection',
    'privacy.stat1.desc': 'We employ institutional-grade encryption for all stored parameters.',
    'privacy.stat2.title': 'Secure Access',
    'privacy.stat2.desc': 'Access to project briefs is restricted to authorized systems architects.',
    'privacy.stat3.title': 'Transparency',
    'privacy.stat3.desc': 'Clear reporting on how your interaction telemetry is utilized.',
    'terms.title': 'Terms of',
    'terms.title_italic': 'Service.',
    'terms.legal_directive': 'Legal Directive 02',
    'terms.last_updated': 'Last updated: June 11, 2026',
    'terms.section1.title': '1. Acceptance of Protocol',
    'terms.section1.desc':
      'By engaging with the NextCreavo system, you acknowledge and agree to be bound by these architectural terms. If you do not align with these parameters, please cease system navigation immediately.',
    'terms.section2.title': '2. Intellectual Framework',
    'terms.section2.desc':
      'All design systems, UI patterns, and structural code provided by NextCreavo remain the intellectual asset of the studio until full capital transfer is executed according to specific project contracts.',
    'terms.section3.title': '3. Service Modification',
    'terms.section3.desc':
      'NextCreavo reserves the right to calibrate, update, or deprecate system features and pricing structures without prior notification, ensuring the ecosystem evolves with technological shifts.',
    'terms.stat1.title': 'Fair Use',
    'terms.stat1.desc': 'System interaction must align with ethical digital construction guidelines.',
    'terms.stat2.title': 'Brief Accuracy',
    'terms.stat2.desc': 'Clients are responsible for the validity of parameters in submitted briefs.',
    'terms.stat3.title': 'Liability',
    'terms.stat3.desc': 'NextCreavo is not responsible for external ecosystem disruptions.',
    'cookies_page.title': 'Cookie',
    'cookies_page.title_italic': 'Policy.',
    'cookies_page.legal_directive': 'Legal Directive 03',
    'cookies_page.last_updated': 'Last updated: June 11, 2026',
    'cookies_page.section1.title': '1. Identifier Purpose',
    'cookies_page.section1.desc':
      'We utilize cookies to remember your workspace settings, language preferences, and to secure your session identifiers during project brief submission.',
    'cookies_page.section2.title': '2. Performance Metrics',
    'cookies_page.section2.desc':
      'Anonymous telemetry allows us to measure interaction speeds and optimize visual rendering pipelines across different device architectures.',
    'cookies_page.section3.title': '3. Control Mechanisms',
    'cookies_page.section3.desc':
      'You can calibrate your cookie parameters through your browser settings. Note that disabling essential cookies may destabilize some system features.',
    'cookies_page.stat1.title': 'Session Persistence',
    'cookies_page.stat1.desc': 'Maintaining your localized parameters across digital transitions.',
    'cookies_page.stat2.title': 'Performance Logs',
    'cookies_page.stat2.desc': 'Anonymized telemetry to optimize visual loading speeds.',
    'cookies_page.stat3.title': 'Security Tokens',
    'cookies_page.stat3.desc': 'Protecting brief identifiers from unauthorized vector access.',
    'timeline.tagline': 'Execution Roadmap',
    'timeline.title': 'Project',
    'timeline.title_italic': 'Milestones.',
    'timeline.phase1.phase': 'Phase 01',
    'timeline.phase1.title': 'Discovery & Brief',
    'timeline.phase1.desc': 'Deep dive into brand objectives and ecosystem requirements.',
    'timeline.phase2.phase': 'Phase 02',
    'timeline.phase2.title': 'Architectural Blueprint',
    'timeline.phase2.desc': 'Structuring user flows and high-fidelity interface wireframes.',
    'timeline.phase3.phase': 'Phase 03',
    'timeline.phase3.title': 'Engineering & Craft',
    'timeline.phase3.desc': 'Transformation of design into high-performance digital engines.',
    'timeline.phase4.phase': 'Phase 04',
    'timeline.phase4.title': 'Validation & Launch',
    'timeline.phase4.desc': 'Rigorous benchmarking and global edge deployment.',
  },
  FR: {
    'nav.about': 'À Propos',
    'nav.portfolio': 'Portfolio',
    'nav.services': 'Services',
    'nav.pricing': 'Tarifs',
    'nav.faq': 'FAQ',
    'nav.blog': 'Blog',
    'nav.menu': 'Menu',
    'nav.contact': 'Contact',
    'hero.status': 'Disponible pour de nouveaux projets',
    'hero.title_p1': 'Façonner des',
    'hero.title_p2': 'écosystèmes',
    'hero.title_p3': 'pour les marques modernes.',
    'hero.desc':
      'Nous opérons à l’intersection du design élégant, de la technologie de pointe et de la stratégie profonde pour créer des expériences de marque qui captivent et convertissent.',
    'hero.cta_work': 'Voir nos travaux',
    'hero.cta_services': 'Nos Services',
    'hero.stat_startups': 'Startups Financées',
    'hero.stat_awards': 'Prix de l’Industrie',
    'work.tagline': 'Comment nous innovons.',
    'work.desc':
      'Une méthodologie raffinée en quatre étapes conçue pour transformer votre vision en une expérience numérique de classe mondiale.',
    'work.step1.title': 'Stratégie',
    'work.step1.desc':
      'Découvrir les valeurs fondamentales de votre marque, votre public cible et votre positionnement pour poser des bases solides de croissance.',
    'work.step2.title': 'Maquettage',
    'work.step2.desc':
      'Tracer le parcours utilisateur et la structure pour assurer une expérience utilisateur fluide et intuitive.',
    'work.step3.title': 'Design',
    'work.step3.desc':
      'Créer une interface élégante, visuellement époustouflante et hautement polie qui résonne avec vos utilisateurs.',
    'work.step4.title': 'Développement',
    'work.step4.desc':
      'Ingénierie de solutions évolutives et performantes utilisant les dernières piles technologiques et des mouvements élégants.',
    'projects.title': 'Travaux',
    'projects.title_italic': 'sélectionnés.',
    'projects.cta': 'Voir le Répertoire',
    'services.title': 'Solutions',
    'services.title_italic': 'complètes',
    'services.title_p2': 'pour faire croître votre marque.',
    'services.desc':
      'Nous fournissons une suite complète de services numériques élégants adaptés aux startups et entreprises modernes.',
    'faq.title': 'Demandes',
    'faq.title_italic': 'Système.',
    'faq.tagline': 'Questions Fréquemment Posées',
    'faq.main_title': 'Demandes courantes,',
    'faq.title_italic_resolved': 'résolues.',
    'faq.desc':
      'Trouvez des réponses concernant les délais de traitement des projets, les configurations de vitesse de performance headless, les flux de travail de conception et les calendriers de paiement des jalons.',
    'faq.search_placeholder': 'Rechercher des délais, piles technologiques, GMB, paiements...',
    'faq.items.timeline.q': 'Combien de temps prend un projet typique ?',
    'faq.items.timeline.a':
      "La plupart des projets de développement web personnalisé et de storytelling de marque s'étalent sur 4 à 8 semaines. Les applications hautement personnalisées avec des intégrations multi-agents avancées peuvent nécessiter 10 à 14 semaines, de l'audit initial au déploiement en direct.",
    'faq.items.kickoff.q': 'Quel est votre workflow typique de lancement de projet ?',
    'faq.items.kickoff.a':
      "Nous commençons par un audit approfondi de vos concurrents, des vitesses de page et des exigences techniques. Une fois la phase de blueprint finalisée, nous construisons des maquettes visuelles réactives, avant de passer au développement au pixel près et à l'analyse comparative des performances.",
    'faq.items.comms.q': 'Comment gérez-vous les communications et le partage de fichiers ?',
    'faq.items.comms.a':
      'Nous attribuons un espace de travail Slack dédié et organisons des revues vidéo hebdomadaires. Tous les designs sont entièrement consultables sur Figma, et nos journaux de développement sont régulièrement poussés vers des environnements de test pour un suivi actif.',
    'faq.items.figma.q': 'Concevez-vous des fichiers dans Figma, ou codez-vous directement ?',
    'faq.items.figma.a':
      "Nous faisons les deux. Nous construisons des systèmes de conception de mise en page robustes dans Figma. Une fois approuvés, nous les transformons en code propre à l'aide de modules React, Webflow ou Shopify modulaires.",
    'faq.items.shopify.q': 'Pouvez-vous aider à optimiser les marges de notre boutique Shopify ?',
    'faq.items.shopify.a':
      "Oui. Nous créons des vitrines e-commerce headless personnalisées utilisant l'API Shopify Storefront associée à des systèmes CMS rapides comme Sanity. Cela réduit les temps de chargement, améliore la visibilité de recherche et augmente les finalisations d'achat.",
    'faq.items.gmb.q': "Qu'inclut l'optimisation du classement GMB Map Stack ?",
    'faq.items.gmb.a':
      "Notre séquence de référencement local audite les coordonnées en double, aligne les conventions de nommage des citations, configure les données de schéma localisées et structure les processus d'examen local automatisés.",
    'faq.items.headless.q': 'Pourquoi préférez-vous les modèles de développement découplés et headless ?',
    'faq.items.headless.a':
      'Les structures web découplées séparent la couche de présentation du back-end. Cela signifie que les opérations de base de données ne retardent jamais le chargement visuel. La performance augmente, le poids des pages diminue et la sécurité est renforcée.',
    'faq.items.security.q': "J'ai des bases de données sensibles. Comment protégez-vous les clés API ?",
    'faq.items.security.a':
      'Nous utilisons des architectures multi-tiers sécurisées où les clés API (Gemini, Stripe, etc.) résident toujours sur des serveurs node isolés. Elles ne sont jamais envoyées au navigateur client, empêchant toute exploitation de jeton.',
    'faq.items.motion.q': "Comment le moteur sonore et d'animation fonctionne-t-il si fluidement ?",
    'faq.items.motion.a':
      'Nous évitons les fichiers vidéo lourds. Les flips de livres et les micro-interactions de marque sont programmés en SVG pur et en coordonnées de chemin vectorielles animées via des bibliothèques légères (comme GSAP) fonctionnant sur les threads GPU.',
    'faq.items.billing_structure.q': 'Quelle est votre structure de paiement et de jalons ?',
    'faq.items.billing_structure.a':
      "Nous travaillons généralement sur une structure de jalons claire : 50% d'acompte pour commencer les audits et les plans visuels, et 50% après la validation finale de l'utilisateur et le déploiement.",
    'faq.items.maintenance.q': "Offrez-vous la maintenance, l'hébergement et le support après le lancement ?",
    'faq.items.maintenance.a':
      'Absolument. Nous proposons des forfaits de maintenance mensuels sur mesure incluant audits de sécurité, mises à jour des dépendances, rafraîchissements de mise en page et rapports de trafic.',
    'faq.unresolved.tag': 'Problème non résolu ?',
    'faq.unresolved.title': 'Vous avez des questions spécifiques concernant votre modèle d’entreprise ?',
    'faq.unresolved.desc':
      'Nos partenaires de support et fondateurs répondent directement aux briefs de projet personnalisés sous 12 heures. Soumettez les détails ci-dessous ou lancez un chat client directement sur Slack.',
    'faq.unresolved.cta_brief': 'Établir un brief de projet personnalisé',
    'faq.unresolved.cta_email': 'Email direct',
    'faq.no_results': 'Aucune requête correspondante trouvée',
    'faq.no_results_desc':
      'Nous n’avons trouvé aucune réponse ciblant "{query}". Essayez de chercher d’autres termes comme "Shopify", "paiements" ou "délais".',
    'faq.clear_filters': 'Effacer les filtres de recherche',
    'blog.title': 'Dernières',
    'blog.title_italic': 'Réflexions.',
    'blog.tagline': 'Actualités & Éditorial',
    'blog.main_title': 'Réflexions du',
    'blog.title_italic_resolved': 'syndicat numérique.',
    'blog.desc':
      'Documenter les jalons de l’ingénierie, les références de micro-interaction, les formules de dimensionnement des fichiers vectoriels et les flux de travail marketing IA.',
    'blog.journal_tag': 'NextCreavo Journal',
    'blog.search_placeholder': 'Filtrer par mots-clés, tech ou design...',
    'blog.featured': 'REFLEXION MISE EN AVANT',
    'blog.read_article': 'Lire l’article',
    'blog.no_results': 'Aucune réflexion trouvée correspondant à votre requête.',
    'blog.clear_filters': 'Effacer les filtres',
    'contact.tagline': 'Moteur de Briefing Système',
    'contact.title1': 'Initiez votre design',
    'contact.title_italic': 'manifesto.',
    'contact.desc':
      'Soumettez vos exigences stratégiques ci-dessous. Notre groupe d’architectes de design, d’ingénieurs et de spécialistes des systèmes numériques construira la feuille de route de votre projet.',
    'contact.form.name': 'Nom Légal Complet',
    'contact.form.email': 'Adresse E-mail Sécurisée',
    'contact.form.service': 'Vertical de Service de Base',
    'contact.form.industry': 'Secteur d’Activité de la Marque',
    'contact.form.budget': 'Allocation des Ressources Cibles',
    'contact.form.date': 'Date d’Implémentation Idéale',
    'contact.form.message': 'Vision et Paramètres du Projet',
    'contact.form.submit': 'Transmettre le Brief Projet',
    'contact.form.submitting': 'Transmission...',
    'contact.form.success_title': 'Brief Reçu avec Succès.',
    'contact.form.success_desc':
      'La feuille de route de votre projet est en cours de rédaction. Un stratège vous contactera dans les 24 heures.',
    'contact.info.title': 'Coordonnées de Support',
    'contact.info.desc': 'Canaux directs pour un support architectural immédiat ou des demandes mondiales.',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'footer.cookies': 'Cookies',
    'footer.tagline': 'Une idée ?',
    'footer.tagline_secondary': 'Construisons-la.',
    'cta.brief': 'Lancer le Brief Projet',
    'cta.book': 'Réserver un rendez-vous',
    'ui.social_feeds': 'Flux Sociaux',
    'ui.coordinates': 'Coordonnées',
    'ui.system_navigation': 'Navigation Système',
    'ui.available': 'Disponible pour de nouveaux projets',
    'testimonials.title': 'Retours',
    'testimonials.title_italic': 'Exécutifs.',
    'testimonials.tagline': 'Témoignages Clients',
    'about.tagline': 'La Synthèse NextCreavo',
    'about.title1': 'Formuler des chefs-d’œuvre',
    'about.title2': 'numériques avec',
    'about.title_italic': 'artistry.',
    'about.desc':
      'Opérant à l’intersection des mises en page visuelles suisses, de la performance multi-dispositifs native et des pipelines d’agents intelligents. Nous construisons des produits numériques évolutifs qui remodèlent les trajectoires des marques.',
    'about.hero_stats': 'Précision de l’architecture organisée dans des laboratoires numériques.',
    'about.values_tag': 'NOTRE BOUSSOLE',
    'about.values_title': 'Valeurs sans compromis,',
    'about.values_italic': 'conçues pour inspirer',
    'about.values_desc':
      'Nous rejetons les modèles visuels et la programmation lente. Notre équipe s’aligne derrière quatre plans fondamentaux pour assurer l’intégrité numérique.',
    'about.pipeline_tag': 'Notre Pipeline',
    'about.pipeline_title': 'Le pipeline de la',
    'about.pipeline_italic': 'création de précision.',
    'about.pipeline_desc':
      'Nous structurons notre cycle de vie de projet pour minimiser les délais, optimiser le poids de performance et garantir la précision des pixels.',
    'about.mission_tag': 'NOTRE MISSION',
    'about.mission_title': 'Inspirer, innover et élever les marques numériques.',
    'about.mission_desc':
      'Nous concevons des écosystèmes numériques qui forgent des connexions instantanées avec des partenaires du monde entier. Notre objectif est de repousser les limites visuelles, de valider des statistiques de performance absolues et de partager continuellement nos méthodologies.',
    'about.vision_tag': 'NOTRE VISION',
    'about.vision_title': 'Axé sur la perfection visuelle.',
    'about.vision_desc':
      'Être la première agence numérique reconnue mondialement pour un engagement indéfectible envers l’artisanat. NextCreavo traite chaque engagement client comme un chef-d’œuvre potentiel.',
    'about.team_tag': 'Les Stratèges',
    'about.team_title': 'Rencontrez les esprits derrière',
    'portfolio.listing_tag': 'ARCHIVES SÉLECTIONNÉES',
    'portfolio.listing_title_part1': "L'archive des",
    'portfolio.listing_title_part2': 'références numériques.',
    'portfolio.listing_desc':
      'Une collection curatée de projets d’ingénierie axés sur le design qui définissent le standard de performance NextCreavo.',
    'portfolio.categories.all': 'Toutes les archives',
    'portfolio.categories.animation': 'Animation 2D',
    'portfolio.categories.marketing': 'Marketing Numérique',
    'portfolio.categories.webdev': 'Développement Web',
    'portfolio.categories.appdev': 'Développement d’Apps',
    'portfolio.categories.ai': 'IA et Intégrations',
    'portfolio.categories.desc.animation': 'Mouvement vectoriel fluide et interactions basées sur Lottie.',
    'portfolio.categories.desc.marketing': 'Tunnels de conversion élevée et systèmes de proéminence SEO.',
    'portfolio.categories.desc.webdev': 'Architectures headless de précision et charges utiles React rapides.',
    'portfolio.categories.desc.appdev': 'Expériences mobiles natives avec intégrité multi-plateforme.',
    'portfolio.categories.desc.ai': 'Canaux d’agents intelligents et automatisation alimentée par GPT.',
    'portfolio.viewer_tag': 'VISUALISEUR IMMERSIF',
    'portfolio.viewer_title': 'Modèle d’Actif de Marque 3D',
    'portfolio.viewer_interactive': 'NOEUD INTERACTIF',
    'portfolio.viewer_instructions': 'Faites glisser pour pivoter • Faites défiler pour zoomer',
    'portfolio.share_case': 'Partager l’étude de cas',
    'portfolio.ready_inspect_next': 'Prêt à inspecter le prochain',
    'portfolio.see_how_resolved': 'Découvrez comment nous avons résolu les défis pour',
    'portfolio.launch_next': 'Lancer la prochaine vitrine',
    'portfolio.title': 'La Vitrine',
    'portfolio.tagline': 'Façonner des écosystèmes numériques pour les marques modernes.',
    'portfolio.back_to_grid': 'Retour à la Grille',
    'portfolio.prev_case': 'Cas Précédent',
    'portfolio.next_case': 'Cas Suivant',
    'portfolio.desktop_pre': 'Aperçu Bureau',
    'portfolio.mobile_pre': 'Aperçu Mobile',
    'portfolio.client_chronicle': 'Chronique du Succès Client',
    'portfolio.account_partner': 'Partenaire de Compte',
    'portfolio.transit_timeline': 'Calendrier de Transit',
    'portfolio.live_link': 'Lien vers l’Environnement Direct',
    'portfolio.strategic_brief': 'Brief de Diagnostic Stratégique',
    'portfolio.pinnacle_obstacle': 'Obstacle Majeur',
    'portfolio.technical_formulation': 'Formulation Technique',
    'portfolio.verified_outcomes': 'Objectifs de Résultats Vérifiés',
    'portfolio.aesthetic_swatches': 'Échantillons de Formules Esthétiques',
    'portfolio.aesthetic_desc':
      'Direction visuelle unique structurée en alignement avec l’ergonomie visuelle de l’utilisateur. Cliquez sur n’importe quelle coordonnée pour copier les valeurs instantanément.',
    'portfolio.workflow_roadmap': 'Feuille de Route du Workflow',
    'portfolio.infrastructure_toolkit': 'Boîte à Outils d’Ingrédients d’Infrastructure',
    'portfolio.infrastructure_desc':
      'Architecturé selon les normes de pointe en matière de développement pour garantir la réactivité, le faible poids de bande passante et la haute performance.',
    'portfolio.launch_live': 'Lancer l’Expérience en Direct',
    'portfolio.return_to_directory': 'Retourner au Répertoire',
    'portfolio.next_chronicle': 'CHRONIQUE DE LA PROCHAINE ÉTUDE DE CAS',
    'portfolio.interactive_grid': 'mise en page en grille interactive',
    'portfolio.designed_by_desc':
      'Conçu, compressé et programmé par NextCreavo pour fonctionner en douceur sur les réseaux à faible débit et dans des conditions mobiles à haute latence.',
    'portfolio.hover_to_scroll': 'Survoler pour Faire Défiler',
    'portfolio.category_overview': 'Aperçu de la Catégorie',
    'portfolio.interactive_case_studio': 'Studio de Cas Interactif',
    'portfolio.no_projects_found': 'Aucun projet correspondant trouvé',
    'portfolio.no_projects_desc_part1': 'Nous n’avons trouvé aucune réalisation pour ',
    'portfolio.no_projects_desc_part2':
      'dans la catégorie sélectionnée. Vérifiez l’orthographe ou effacez les filtres de recherche.',
    'portfolio.reset_filters': 'Réinitialiser tous les filtres',
    'cookies.title': 'Consentement aux Cookies',
    'cookies.desc':
      'Ce site web utilise des cookies pour améliorer votre expérience utilisateur et analyser notre trafic.',
    'cookies.accept': 'Tout Accepter',
    'cookies.details': 'Paramètres des Cookies',
    'privacy.title': 'Confidentialité',
    'privacy.title_italic': 'Politique.',
    'privacy.last_updated': 'Dernière mise à jour : 11 juin 2026',
    'privacy.legal_directive': 'Directive Légale 01',
    'privacy.section1.title': '1. Collecte d’Informations',
    'privacy.section1.desc':
      'NextCreavo collecte les informations nécessaires pour fournir des services numériques sur mesure. Cela inclut les identifiants fournis lors du processus de soumission du brief et la télémétrie automatisée recueillie lors de la navigation dans le système.',
    'privacy.section2.title': '2. Utilisation des Paramètres',
    'privacy.section2.desc':
      'Vos données sont traitées pour faciliter la construction de la feuille de route du projet, stabiliser les communications du système et personnaliser l’expérience architecturale. Nous ne transmettons pas d’identifiants à des écosystèmes de données tiers à des fins publicitaires.',
    'privacy.section3.title': '3. Architecture de Sécurité',
    'privacy.section3.desc':
      'Nous maintenons un protocole de sécurité multicouche. La transmission des briefs s’effectue via des tunnels cryptés TLS 1.3. Les données persistantes sont isolées dans des environnements Cloud SQL et Firestore surveillés.',
    'privacy.stat1.title': 'Protection des Données',
    'privacy.stat1.desc': 'Nous utilisons un cryptage de niveau institutionnel pour tous les paramètres stockés.',
    'privacy.stat2.title': 'Accès Sécurisé',
    'privacy.stat2.desc': 'L’accès aux briefs de projet est limité aux architectes système autorisés.',
    'privacy.stat3.title': 'Transparence',
    'privacy.stat3.desc': 'Rapports clairs sur la manière dont votre télémétrie d’interaction est utilisée.',
    'terms.title': 'Conditions de',
    'terms.title_italic': 'Service.',
    'terms.legal_directive': 'Directive Légale 02',
    'terms.last_updated': 'Dernière mise à jour : 11 juin 2026',
    'terms.section1.title': '1. Acceptation du Protocole',
    'terms.section1.desc':
      'En engageant avec le système NextCreavo, vous reconnaissez et acceptez d’être lié par ces conditions architecturales. Si vous ne vous alignez pas avec ces paramètres, veuillez cesser immédiatement la navigation dans le système.',
    'terms.section2.title': '2. Cadre Intellectuel',
    'terms.section2.desc':
      'Tous les systèmes de conception, les modèles d’interface utilisateur et le code structurel fournis par NextCreavo restent l’actif intellectuel du studio jusqu’à ce que le transfert de capital complet soit exécuté conformément aux contrats de projet spécifiques.',
    'terms.section3.title': '3. Modification du Service',
    'terms.section3.desc':
      'NextCreavo se réserve le droit de calibrer, mettre à jour ou déprécier les fonctionnalités du système et les structures de prix sans notification préalable, garantissant que l’écosystème évolue avec les changements technologiques.',
    'terms.stat1.title': 'Usage Équitable',
    'terms.stat1.desc':
      'L’interaction avec le système doit être conforme aux directives éthiques de construction numérique.',
    'terms.stat2.title': 'Précision du Brief',
    'terms.stat2.desc': 'Les clients sont responsables de la validité des paramètres dans les briefs soumis.',
    'terms.stat3.title': 'Responsabilité',
    'terms.stat3.desc': 'NextCreavo n’est pas responsable des perturbations des écosystèmes externes.',
    'cookies_page.title': 'Politique de',
    'cookies_page.title_italic': 'Cookies.',
    'cookies_page.legal_directive': 'Directive Légale 03',
    'cookies_page.last_updated': 'Dernière mise à jour : 11 juin 2026',
    'cookies_page.section1.title': '1. Objectif de l’Identifiant',
    'cookies_page.section1.desc':
      'Nous utilisons des cookies pour mémoriser vos paramètres d’espace de travail, vos préférences linguistiques et pour sécuriser vos identifiants de session lors de la soumission du brief de projet.',
    'cookies_page.section2.title': '2. Métriques de Performance',
    'cookies_page.section2.desc':
      'La télémétrie anonyme nous permet de mesurer les vitesses d’interaction et d’optimiser les pipelines de rendu visuel sur différentes architectures d’appareils.',
    'cookies_page.section3.title': '3. Mécanismes de Contrôle',
    'cookies_page.section3.desc':
      'Vous pouvez calibrer vos paramètres de cookies via les paramètres de votre navigateur. Notez que la désactivation des cookies essentiels peut déstabiliser certaines fonctionnalités du système.',
    'cookies_page.stat1.title': 'Persistance de Session',
    'cookies_page.stat1.desc': 'Maintien de vos paramètres localisés à travers les transitions numériques.',
    'cookies_page.stat2.title': 'Journaux de Performance',
    'cookies_page.stat2.desc': 'Télémétrie anonymisée pour optimiser les vitesses de chargement visuel.',
    'cookies_page.stat3.title': 'Jetons de Sécurité',
    'cookies_page.stat3.desc': 'Protection des identifiants de brief contre les accès vectoriels non autorisés.',
    'timeline.tagline': 'Feuille de Route d’Exécution',
    'timeline.title': 'Jalons du',
    'timeline.title_italic': 'Projet.',
    'timeline.phase1.phase': 'Phase 01',
    'timeline.phase1.title': 'Découverte & Brief',
    'timeline.phase1.desc': 'Plongée profonde dans les objectifs de la marque et les exigences de l’écosystème.',
    'timeline.phase2.phase': 'Phase 02',
    'timeline.phase2.title': 'Plan Architectural',
    'timeline.phase2.desc': 'Structuration des flux utilisateurs et des maquettes d’interface haute fidélité.',
    'timeline.phase3.phase': 'Phase 03',
    'timeline.phase3.title': 'Ingénierie & Artisanat',
    'timeline.phase3.desc': 'Transformation du design en moteurs numériques haute performance.',
    'timeline.phase4.phase': 'Phase 04',
    'timeline.phase4.title': 'Validation & Lancement',
    'timeline.phase4.desc': 'Analyse comparative rigoureuse et déploiement mondial.',
  },
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN')

  const t = (key: string) => {
    return translations[language][key] || key
  }

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
